version: "3.9"

services:
  app:
    image: cloudbooking:v0.3.0
    env_file:
      - .env
    depends_on: [mongo]
    networks: [cloudbooking_net]
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        monitor: 10s
        failure_action: rollback
        max_failure_ratio: 0.1
      rollback_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5055/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  mongo:
    image: mongo:6
    command: ["--bind_ip_all"]
    volumes:
      - mongo_data:/data/db
    networks: [cloudbooking_net]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        order: start-first
      rollback_config:
        parallelism: 1
        order: stop-first
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 15s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - /opt/app/cloudbooking/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/app/cloudbooking/web:/usr/share/nginx/html:ro
    depends_on: [app]
    networks: [cloudbooking_net]
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        monitor: 10s
        failure_action: rollback
      rollback_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  mongo_data: {}

networks:
  cloudbooking_net:
    driver: overlay
