# cloudbooking-stack.yml
version: "3.9"

services:
  app:
    image: cloudbooking:latest
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - cloudbooking_net
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        max_replicas_per_node: 3

  mongo:
    image: mongo:6
    command: ["--bind_ip_all"]
    volumes:
      - mongo_data:/data/db
    networks:
      - cloudbooking_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web:/usr/share/nginx/html:ro
    depends_on:
      - app
    networks:
      - cloudbooking_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  mongo_data: {}

networks:
  cloudbooking_net:
    driver: overlay
