version: "3.9"

services:
  app:
    # 用你“实际存在的镜像标签”
    # 你目前成功构建的是 GHCR 的 0.1.0；0.6.0 还没有
    image: ghcr.io/taoc3860-pixel/cloudbooking:0.1.0
    env_file:
      - .env
    environment:
      - PORT=5055
      # 如需临时排障可开启：
      # - MONGOOSE_DEBUG=1
    networks: [cloudbooking_net]
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        monitor: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
    healthcheck:
      # 你的后端是 /healthz，不是 /health
      test: ["CMD", "wget", "-qO-", "http://localhost:5055/healthz"]
      interval: 10s
      timeout: 3s
      retries: 5

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - /opt/app/cloudbooking/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/app/cloudbooking/web:/usr/share/nginx/html:ro
    depends_on: [app]
    networks: [cloudbooking_net]
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        monitor: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/"]
      interval: 10s
      timeout: 3s
      retries: 5

networks:
  cloudbooking_net:
    driver: overlay
