services:
  app:
    build:
      context: .
      dockerfile: Dockerfile   # 确认大小写与仓库一致
    image: cloudbooking:0.8.0  # 版本你自己定，保持前后一致即可
    env_file: [.env]
    # app 不对外暴露端口，由 nginx 反代即可
    # ports:
    #   - "5055:5055"

  nginx:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web:/usr/share/nginx/html:ro  # <== 让 nginx 看到你的静态文件
