version: "3.8"
services:
  web:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./web:/usr/share/nginx/html:ro         # 静态资源
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks: [appnet]

  api:
    build: .
    env_file: .env
    volumes:
      - cloudbooking_data:/app/data            # 持久化 users.json/bookings.json
    networks: [appnet]

volumes:
  cloudbooking_data:

networks:
  appnet:
