services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cloudbooking:0.8.0
    env_file: [.env]
    ports:
      - "5055:5055"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on: [app]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web:/usr/share/nginx/html:ro
