version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile   # 如果你的 Dockerfile 在 backend/ 目录，请改成 backend/Dockerfile
    container_name: cloudbooking_app
    env_file: .env
    ports:
      - "5055:5055"
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:6
    container_name: cloudbooking_mongo
    volumes:
      - mongo_data:/data/db
    restart: always

  nginx:
    image: nginx:alpine
    container_name: cloudbooking_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web:/usr/share/nginx/html:ro
    depends_on:
      - app
    restart: always

volumes:
  mongo_data:
